### ISSUE TITLE
beet --version returns natsort error

### ISSUE THREAD

**Issue by trustosas** [Neurrone/beets-audible#31]
```python
/usr/local/lib/python3.7/dist-packages/beets/mediafile.py:19: UserWarning: beets.mediafile is deprecated; use mediafile instead
  warnings.warn("beets.mediafile is deprecated; use mediafile instead")
** error loading plugin audible:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/beets/plugins.py", line 268, in load_plugins
    namespace = __import__(modname, None, None)
  File "/content/beets-audible/audible.py", line 13, in <module>
    from natsort import os_sorted
ImportError: cannot import name 'os_sorted' from 'natsort' (/usr/local/lib/python3.7/dist-packages/natsort/__init__.py)

beets version 1.6.0
Python version 3.7.13
plugins: copyartifacts, edit, fromfilename, scrub
```

What do I do to fix it?

**Comment by trustosas** [comment]
Solution was to uninstall and reinstall natsort package with pip
