### ISSUE TITLE
errors while processing file

### ISSUE THREAD

**Issue by kcossabo** [Neurrone/beets-audible#58]
For the most part the install is working well, Thank You. 

```
/untagged/Colin Powell (1 items)
Finding tags for album "Colin Powell - Colin Powell".
Candidates:
1. Bud Powell - Strictly Powell (25.4%) (missing tracks, album, artist, ...) (1982, FR)
2. Jesse Powell - Jesse Powell (23.6%) (missing tracks, tracks, album, ...) (CD, 1996, US, MCA Records, 11287)
3. Jesse Powell - Jesse Powell (23.6%) (missing tracks, tracks, album, ...) (Digital Media, 1996, CA, Silas)
4. Bud Powell - Strictly Powell (23.3%) (missing tracks, album, artist, ...) (Digital Media, 1957, XW, RCA)
5. Bud Powell - Bud Powell (17.9%) (missing tracks, tracks, album, ...) (CD, 2001, Giants of Jazz, CD 53362)
# selection (default 1), Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort, eDit, edit Candidates? Error while requesting https://api.audnex.us/books/B08L39TTVK/chapters, attempt 1/3: status code 404, Not Found
Error while requesting https://api.audnex.us/books/B08L39TTVK/chapters, attempt 2/3: status code 404, Not Found
Error while requesting https://api.audnex.us/books/B08L39TTVK/chapters, attempt 3/3: status code 404, Not Found
audible: Error while fetching book information from Audnex
Traceback (most recent call last):
  File "/plugins/audible/audible.py", line 255, in get_albums
    return [self.get_album_info(p["asin"]) for p in products_without_unreleased_entries]
  File "/plugins/audible/audible.py", line 255, in <listcomp>
    return [self.get_album_info(p["asin"]) for p in products_without_unreleased_entries]
  File "/plugins/audible/audible.py", line 264, in get_album_info
    (book, chapters) = get_book_info(asin)
  File "/plugins/audible/api.py", line 25, in get_book_info
    chapter_response = json.loads(make_request(f"{AUDNEX_ENDPOINT}/books/{asin}/chapters"))
  File "/plugins/audible/api.py", line 50, in make_request
    raise e
  File "/plugins/audible/api.py", line 42, in make_request
    with request.urlopen(req) as response:
  File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

This is a download from Audiable, and most seem to tag perfect. This one does not, and the embedded data does not include the actual book / recording name = Colin Powell, An American Hero Speaks out

I changed the file name to "Colin Powell, An American Hero Speaks out" and the above happened.

**Comment by Neurrone** [comment]
Unfortunately, this is something entirely outside my control.

Please file an issue with [Audnexus](https://github.com/laxamentumtech/audnexus), since that is where the plugin gets its info from.
