### ISSUE TITLE
Audnex Error 500, Internal Server Error

### ISSUE THREAD

**Issue by Sparticuz** [Neurrone/beets-audible#6]
I'm receiving an error 500, internal server error on a book. However, the error does not appear to be an Internal Server Error as it's returning a message of `{"statusCode":500,"error":"Internal Server Error","message":"No Chapters"}`, which seems like...not an error... This should probably fail gracefully and just not apply chapters to the files.

https://api.audnex.us/books/B002V8DFQ0/chapters

```
─
Error while requesting https://api.audnex.us/books/B002V8DFQ0/chapters, attempt 1/3: status code 500, Internal Server Error
Error while requesting https://api.audnex.us/books/B002V8DFQ0/chapters, attempt 2/3: status code 500, Internal Server Error
Error while requesting https://api.audnex.us/books/B002V8DFQ0/chapters, attempt 3/3: status code 500, Internal Server Error
audible: Error while fetching book information from Audnex
Traceback (most recent call last):
  File "/config/plugins/beets-audible/audible.py", line 255, in get_albums
    return [self.get_album_info(p["asin"]) for p in products_without_unreleased_entries]
  File "/config/plugins/beets-audible/audible.py", line 255, in <listcomp>
    return [self.get_album_info(p["asin"]) for p in products_without_unreleased_entries]
  File "/config/plugins/beets-audible/audible.py", line 264, in get_album_info
    (book, chapters) = get_book_info(asin)
  File "/config/plugins/beets-audible/api.py", line 25, in get_book_info
    chapter_response = json.loads(make_request(f"{AUDNEX_ENDPOINT}/books/{asin}/chapters"))
  File "/config/plugins/beets-audible/api.py", line 50, in make_request
    raise e
  File "/config/plugins/beets-audible/api.py", line 42, in make_request
    with request.urlopen(req) as response:
  File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error

```

**Comment by Neurrone** [comment]
Thanks for the bug report. I'll see what I can do to make this fall back gracefully to not applying chapter data.

In the meantime, could you report it upstream to https://github.com/laxamentumtech/audnexus/issues

A workaround you can use is to manually specify the metadata in a yaml file, see the readme for details.

**Comment by djdembeck** [comment]
This has been fixed upstream, along with other erroneous return codes.
